org.springframework.boot.actuate.autoconfigure.audit.AuditAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.audit.AuditAutoConfiguration.ConditionalOnBean=org.springframework.boot.actuate.audit.AuditEventRepository
org.springframework.boot.actuate.autoconfigure.audit.AuditEventsEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.audit.AuditEventsEndpointAutoConfiguration.AutoConfigureAfter=org.springframework.boot.actuate.autoconfigure.audit.AuditAutoConfiguration
org.springframework.boot.actuate.autoconfigure.beans.BeansEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.condition.ConditionsReportEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.context.ShutdownEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.context.properties.ConfigurationPropertiesReportEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.endpoint.EndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.endpoint.jackson.Jackson2EndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.endpoint.jackson.Jackson2EndpointAutoConfiguration.ConditionalOnClass=com.fasterxml.jackson.databind.ObjectMapper,org.springframework.http.converter.json.Jackson2ObjectMapperBuilder
org.springframework.boot.actuate.autoconfigure.endpoint.jackson.JacksonEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.endpoint.jackson.JacksonEndpointAutoConfiguration.ConditionalOnClass=tools.jackson.databind.json.JsonMapper
org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration$JmxJackson2EndpointConfiguration=
org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration$JmxJackson2EndpointConfiguration.ConditionalOnClass=com.fasterxml.jackson.databind.ObjectMapper
org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration$JmxJacksonEndpointConfiguration=
org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration$JmxJacksonEndpointConfiguration.ConditionalOnClass=tools.jackson.databind.json.JsonMapper
org.springframework.boot.actuate.autoconfigure.endpoint.jmx.JmxEndpointAutoConfiguration.AutoConfigureAfter=org.springframework.boot.autoconfigure.jmx.JmxAutoConfiguration,org.springframework.boot.actuate.autoconfigure.endpoint.EndpointAutoConfiguration
org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointAutoConfiguration$WebEndpointServletConfiguration=
org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointAutoConfiguration$WebEndpointServletConfiguration.ConditionalOnWebApplication=SERVLET
org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointAutoConfiguration.AutoConfigureAfter=org.springframework.boot.actuate.autoconfigure.endpoint.EndpointAutoConfiguration
org.springframework.boot.actuate.autoconfigure.endpoint.web.WebEndpointAutoConfiguration.ConditionalOnWebApplication=
org.springframework.boot.actuate.autoconfigure.env.EnvironmentEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.info.InfoContributorAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.info.InfoContributorAutoConfiguration.AutoConfigureAfter=org.springframework.boot.autoconfigure.info.ProjectInfoAutoConfiguration
org.springframework.boot.actuate.autoconfigure.info.InfoEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.info.InfoEndpointAutoConfiguration.AutoConfigureAfter=org.springframework.boot.actuate.autoconfigure.info.InfoContributorAutoConfiguration
org.springframework.boot.actuate.autoconfigure.logging.LogFileWebEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.logging.LoggersEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.management.HeapDumpWebEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.management.ThreadDumpEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.sbom.SbomEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.scheduling.ScheduledTasksEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.startup.StartupEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.web.exchanges.HttpExchangesEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.web.mappings.MappingsEndpointAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration=
org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration.AutoConfigureOrder=2147483647
